config/routes.rb
Rails.application.routes.draw do
  resources :channels do
    resources :messages, only: [:create]
    resource :tooltip, only: [:show]
  end

  root 'channels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages, dependent: :destroy

  after_create_commit -> { broadcast_append_to :channels }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel

  after_commit on: :create do
    broadcast_append_to(
      channel,
      partial: 'messages/message',
      locals: { message: self },
      target: 'chat'
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_reader :channel
  alias current_channel channel
  helper_method :current_channel
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channels
  before_action :set_channel, only: %i[ show destroy ]

  # GET /channels
  def index
  end

  # GET /channels/1
  def show
    render action: :index
  end

  # POST /channels
  def create
    @channel = Channel.create(channel_params)

    render partial: 'channels/form'
  end

  # DELETE /channels/:id
  def destroy
    @channel.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@channel) }
      format.html         { redirect_to channels_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    def set_channels
      @channels = Channel.all.order(name: :asc)
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_channel, only: [:create]
  attr_reader :channel

  def create
    Message.create(message_params.merge(author: 'dunno', channel: channel))

    render partial: 'messages/form'
  end

  private

  def set_channel
    @channel = Channel.find(params[:channel_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/tooltips_controller.rb
class TooltipsController < ApplicationController
  def show
    @channel = Channel.find(params[:channel_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/_channel.html.erb
<div id="<%= dom_id channel %>">
  <%
    classes = "rounded-lg py-2 px-5 bg-gray-100 inline-block peer w-full"
    classes += channel == current_channel ? "font-bold" : "font-medium"
  %>
  <div class="<%= classes %> flow-root">
    <div class="float-left">
      <%= link_to "#{channel.name}", channel, aria: { describedby: dom_id(channel, :tooltip) } %>
    </div>
    <div class="float-right">
      <%= button_to channel, method: :delete do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
    <% end %>
    </div>
</div>

  <turbo-frame id="<%= dom_id channel, :tooltip %>" target="_top" role="tooltip"
               src="<%= channel_tooltip_path(channel, turbo_frame: dom_id(channel, :tooltip)) %>"
               class="hidden absolute translate-y-[-200%] z-10
                     peer-hover:block peer-focus:block hover:block focus-within:block"
               loading="lazy"
  >
</div>

app/views/channels/_chat.html.erb
<div class="mx-auto">
  <div class="max-w-2xl border rounded">
    <div>
      <div class="w-full">
        <div class="relative flex items-center p-3 border-b border-gray-300">
          <span class="block ml-2 font-bold text-gray-600">
            <% if current_channel %>
              <%= current_channel.name %>
            <% else %>
                No channel selected
            <% end %>
          </span>
        </div>

        <div class="relative w-full p-6 overflow-y-auto h-[40rem]">
          <ul class="space-y-2" id='chat' data-controller="scroll">
            <%= turbo_stream_from current_channel %>
            <%= render current_channel.messages.order(id: :asc) if current_channel %>
          </ul>
        </div>

        <div class="flex items-center justify-between w-full p-3 border-t border-gray-300">
            <%= render 'messages/form' if current_channel %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/channels/_form.html.erb
<turbo-frame id="<%= dom_id(Channel.new, :form) %>">
  <%= form_for [Channel.new] do |f| %>
    <div class="container flex justify-center items-center">
        <div class="relative">
          <div class="absolute top-4 left-3">
            <i class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i>
          </div>
          <%= f.text_field :name, placeholder: 'new channel', class: 'placeholder-gray-500 w-full rounded-full outline-none h-14 w-full pl-5 pr-20' %>
          <div class="absolute top-2 right-2 py-2">
            <%= f.button do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z" clip-rule="evenodd" />
              </svg>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</turbo-frame>

app/views/channels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Channels</h1>
  </div>

  <div class="grid grid-cols-5 gap-3">
    <div class="min-w-full">
      <div id="channels" class="space-y-4">
        <%= turbo_stream_from :channels %>
        <%= render @channels %>
      </div>
      <div class="py-5">
        <%= render 'form' %>
      </div>
    </div>
    <div class="col-span-4">
      <%= render 'chat' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dovid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_with_jwt_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<turbo-frame id="<%= dom_id(current_channel, :form) %>">
  <%= form_for [current_channel, Message.new] do |f| %>
    <div class="container flex justify-center items-center">
        <div class="relative">
          <div class="absolute top-4 left-3">
            <i class="fa fa-search text-gray-400 z-20 hover:text-gray-500"></i>
          </div>
          <%= f.text_field :content, placeholder: 'new message', class: 'bg-gray-100 placeholder-gray-500 w-full rounded-full outline-none h-14 w-full pl-5 pr-20' %>
          <div class="absolute top-2 right-2 py-2">
            <%= f.button do %>
              <svg class="w-5 h-5 text-gray-500 origin-center transform rotate-90" xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20" fill="currentColor">
                <path
                  d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
              </svg>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</turbo-frame>

app/views/messages/_message.html.erb
<li class="flex justify-start">
  <div class="relative max-w-xl px-4 py-2 rounded shadow">
    <span class="block text-grey-700"><%= message.content %></span>
    <span class="block text-xs text-gray-400"><%= message.author %></span>
  </div>
</li>

app/views/tooltips/show.html.erb
<turbo-frame id="<%= params.fetch :turbo_frame, dom_id(@channel, :tooltip) %>" target="_top">
  <div class="relative">
    <div class="flex gap-2 items-center p-1 bg-black rounded-md text-white">
      <strong>message count:</strong>
      <%= @channel.messages.count %>
    </div>
    <div class="h-2 w-2 bg-black rotate-45 -top-1 -left-2 ml-[50%] relative"></div>
  </div>
</turbo-frame>